# Competition Configuration Template
# Copy this file and customize for new competitions

competition_id: your-competition-id
title: "Competition Full Title"

# Data configuration
data:
  train_file: train.csv
  test_file: test.csv
  sample_submission: sample_submission.csv
  # Optional: validation split
  validation_split: 0.2
  stratified: true
  
# Column specifications
columns:
  id: id_column_name
  target: target_column_name
  features:
    - feature1
    - feature2
    # List all feature columns
  
  # Optional: specify categorical columns
  categorical:
    - cat_feature1
    - cat_feature2
  
  # Optional: specify numerical columns
  numerical:
    - num_feature1
    - num_feature2

# Submission configuration
submission:
  id_column: id_column_name
  target_column: target_column_name
  format: csv  # or parquet, json
  encoding: utf-8
  # Optional: post-processing
  post_processing:
    clip_predictions: false
    min_value: null
    max_value: null
    round_decimals: null
  
# Evaluation configuration
evaluation:
  metric: accuracy  # accuracy, f1, auc, rmse, mae, etc.
  higher_is_better: true
  scoring_function: classification_accuracy
  # Optional: class weights for imbalanced data
  class_weights: null
  
# Model configuration suggestions
model:
  suggested_batch_size: 32
  suggested_epochs: 10
  suggested_lr: 2e-5
  augmentation_enabled: false
  task_type: classification  # or regression
  # Optional: model-specific configs
  dropout_rate: 0.1
  hidden_size: 768
  num_attention_heads: 12
  
# Text template configuration
text_template:
  style: "narrative"  # narrative, factual, structured, or custom
  include_missing: true
  max_length: 256
  # Optional: custom template
  custom_template: null
  
# MLflow tracking configuration
mlflow:
  experiment_name_suffix: null
  tags:
    competition_type: tabular
    difficulty: medium
  log_artifacts:
    - predictions
    - feature_importance
    - model_architecture
    
# Advanced options
advanced:
  # Ensemble configuration
  ensemble:
    enabled: false
    models: []
    weights: []
  
  # Cross-validation
  cross_validation:
    enabled: false
    n_folds: 5
    strategy: stratified
  
  # Feature engineering
  feature_engineering:
    create_interactions: false
    polynomial_features: false
    target_encoding: false