# Configuration with compilation disabled
optimizer:
  type: adamw
  learning_rate: 2.0e-5
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.999
  epsilon: 1.0e-8
  max_grad_norm: 1.0

scheduler:
  type: linear
  warmup_steps: 50
  warmup_ratio: 0.1

data:
  batch_size: 32
  eval_batch_size: 64
  num_workers: 4
  prefetch_size: 4
  shuffle_train: true
  drop_last: false
  pin_memory: true
  augment_train: false

training:
  num_epochs: 3
  max_steps: -1
  gradient_accumulation_steps: 1
  mixed_precision: true
  eval_strategy: steps
  eval_steps: 50
  logging_steps: 5
  save_strategy: epoch
  save_steps: 100
  save_total_limit: 3
  save_best_only: true
  best_metric: val_accuracy
  best_metric_mode: max
  early_stopping: true
  early_stopping_patience: 3
  label_smoothing: 0.0
  dropout_rate: 0.1
  use_compilation: false  # Disable compilation

environment:
  output_dir: output
  seed: 42
  device: gpu
  gradient_checkpointing: false
  memory_efficient_attention: true
  debug_mode: false
  profile: false