# Quick test configuration for rapid iteration
optimizer:
  type: adamw
  learning_rate: 5.0e-5
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.999
  epsilon: 1.0e-8
  max_grad_norm: 1.0

scheduler:
  type: none
  warmup_steps: 0
  warmup_ratio: 0.0

data:
  batch_size: 8
  eval_batch_size: 16
  num_workers: 2
  prefetch_size: 2
  shuffle_train: true
  drop_last: false
  pin_memory: true
  augment_train: false

training:
  num_epochs: 1
  max_steps: -1
  gradient_accumulation_steps: 1
  mixed_precision: true
  eval_strategy: no
  eval_steps: 500
  logging_steps: 10
  save_strategy: epoch
  save_steps: 500
  save_total_limit: 1
  save_best_only: false
  early_stopping: false
  label_smoothing: 0.0
  dropout_rate: 0.1

environment:
  output_dir: output/quick_test
  seed: 42
  device: gpu
  gradient_checkpointing: false
  memory_efficient_attention: true
  debug_mode: true
  profile: false