custom: {}
data:
  augment_train: false
  augmentation_prob: 0.5
  batch_size: 4
  drop_last: false
  eval_batch_size: 8
  num_workers: 2
  pin_memory: true
  prefetch_size: 2
  shuffle_train: true
environment:
  debug_mode: false
  device: gpu
  experiment_name: no_hooks_test
  gradient_checkpointing: false
  memory_efficient_attention: true
  mlflow_experiment_id: null
  mlflow_tags: {}
  mlflow_tracking_uri: null
  output_dir: no_hooks_test_output
  profile: false
  run_name: null
  seed: 42
optimizer:
  beta1: 0.9
  beta2: 0.999
  epsilon: 1.0e-08
  gradient_clip_val: null
  learning_rate: 5.0e-05
  lion_beta1: 0.9
  lion_beta2: 0.99
  max_grad_norm: 1.0
  momentum: 0.9
  nesterov: false
  type: adamw
  weight_decay: 0.01
scheduler:
  factor: 0.5
  gamma: 0.95
  min_lr: 1.0e-07
  mode: min
  num_cycles: 0.5
  num_restarts: 1
  num_training_steps: null
  patience: 5
  power: 1.0
  threshold: 0.01
  type: none
  warmup_ratio: 0.0
  warmup_steps: 0
training:
  best_metric: eval_loss
  best_metric_mode: min
  dropout_rate: 0.1
  early_stopping: false
  early_stopping_patience: 3
  early_stopping_threshold: 0.0001
  eval_delay: 0
  eval_steps: 500
  eval_strategy: 'no'
  gradient_accumulation_steps: 1
  label_smoothing: 0.0
  log_level: info
  logging_steps: 10
  max_steps: -1
  mixed_precision: true
  num_epochs: 1
  report_to: []
  save_best_only: false
  save_steps: 500
  save_strategy: epoch
  save_total_limit: 3
