name: CLI Contract Tests

on:
  push:
    paths:
      - 'cli/**'
      - 'utils/**'
      - 'models/**'
      - 'tests/cli/**'
      - '.github/workflows/cli-contract-tests.yml'
  pull_request:
    paths:
      - 'cli/**'
      - 'utils/**'
      - 'models/**'
      - 'tests/cli/**'

jobs:
  contract-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        uv venv
        uv pip sync requirements.txt
        uv pip install pytest pytest-cov pytest-mock
    
    - name: Run contract tests
      run: |
        uv run pytest tests/cli/test_api_contracts.py -v --tb=short
    
    - name: Check contract coverage
      run: |
        uv run python run_contract_tests.py
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: contract-test-results-${{ matrix.python-version }}
        path: |
          .pytest_cache/
          htmlcov/
    
    - name: Comment PR
      if: failure() && github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '❌ CLI Contract Tests Failed!\n\nThe API contracts between CLI and utilities have been broken. Please review the test failures and update either the code or the contracts in `docs/CLI_API_CONTRACTS.md`.'
          })